matrix:
  include:
   - language: python
     python:
      - "3.4"
      - "3.5"
      - "3.6"
     script:
      - sh run_travis.sh
      
    - language: node_js
        - "iojs"
        - "7"
#      before_script:
#        - cd frontend
#        - npm install
      script:
        - npm run build
#      after_script:
#        - cd ..
