language: node_js
node_js:
  - "7"

branches:
  only:
  - master
  - develop

before_script:
  - npm install -g --silent @angular/cli
  - npm install

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ng build --prod; fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then ng build --dev; fi
