matrix:
  include:
   - language: python
     python:
      - "3.4"
      - "3.5"
      - "3.6"
     script:
      - sh run_travis.sh
     after_script:
      - cd ..
      
    - language: node_js
      node_js:
        - "7"
      before_script:
        - cd frontend
        - npm install
      script:
        - ng build
      after_script:
        - cd ..
