matrix:
    - language: node_js
      node_js:
        - "iojs"
        - "7"
      before_script:
        - cd frontend
        - npm install -g --silently @angular/cli
        - npm install
      script:
        - ng build
      after_script:
        - cd ..
